### ISSUE TITLE
[REQ] A Really Simple Queue System

### ISSUE THREAD

**Issue by xNanochip** [Sacchan-VRC/MS-VRCSA-Billiards#2]
Not sure if feature requests are allowed here or not, but a really neat system I'd love to see is a super simple queue of a textbox showing who would like to play next. Often times in clubs and raves, I see a large group of people surrounding a pool table wanting to play, and it'd be neat to see who's in line!

Similar to a real world bar, you would put your coins on the edge of the table indicating you'd like to play next game. This could be done by simply clicking a button and a visual indicator would show "X player would like to play next game" (and a visual stack coins on the side of the table would be neat).

Ideally, this system would be just a text box indicating who would like to play next and that's it. No enforcements or anything as people could stall/prevent others from playing. Feel free to expand on the idea if you want!

**Comment by cheesestudio** [comment]
@xNanochip heres a Variations which support udonchips（import udonchips first and put it in your sence),you can set the entry cost you want,but i didn't make the waiting list part(but there is such a system in the world"RE˸カジュビリ部室”)

//i just put more than 4 tables in my world so nobody need to wait for others
![image](https://github.com/Sacchan-VRC/MS-VRCSA-Billiards/assets/52149451/480d6959-1ba0-4ae4-89cf-04c3d07dc5d5)
https://github.com/cheesestudio/VRChat-Pool-table-with-15-red-snooker-Pyramid-Chinese-8-ball-based-on-MS-VRCSA-Billiards/releases/download/vrchat/UdonChips.support.variation.unitypackage

**Comment by xNanochip** [comment]
Hey that's a neat feature! Though, I think there's a misunderstanding of what I was getting at here. 

The coins aren't for purchasing at all, it's simply just a visual indicator of "hey I have dibs on next game" like at a real world bar's billiards table (maybe that's just a culture thing where I'm at?). Coins aside, the gist of what I'm requesting is a simple way for spectators to queue up so we can see who has dibs on next game while a current game is in progress without the constant need to go around asking/telling people "hey I have dibs on next game!".

Let me know what you think :)

**Comment by Sacchan-VRC** [comment]
Cool idea, but I think it should probably be a separate system / addon to this project, not in the main thing itself.
